---

ci:
  autoupdate_schedule: quarterly  # low frequency to reduce maintenance noise

repos:
- repo: https://github.com/Kludex/no-optional.git
  rev: 0.4.0
  hooks:
  - id: no_optional

- repo: https://github.com/astral-sh/ruff-pre-commit.git
  rev: v0.15.9
  hooks:
  - id: ruff-check
    args:
    # Ref: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    - --exit-non-zero-on-fix
    - --fix  # NOTE: When `--fix` is used, linting should be before ruff-format
    - --show-fixes

- repo: https://github.com/astral-sh/ruff-pre-commit.git
  rev: v0.15.9
  hooks:
  - id: ruff-format  # Cython imports are handled by `isort`
    alias: ruff-format-first-pass
    name: ruff-format (first pass)

- repo: https://github.com/asottile/add-trailing-comma.git
  rev: v4.0.0
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/astral-sh/ruff-pre-commit.git
  rev: v0.15.9
  hooks:
  - id: ruff-format  # Cython imports are handled by `isort`
    alias: ruff-format-second-pass
    name: ruff-format (second pass)

- repo: https://github.com/PyCQA/isort.git
  rev: 8.0.1
  hooks:
  - id: isort
    args:
    - --honor-noqa
    types_or:
    - cython  # Python is handled by Ruff

- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.5.6
  hooks:
  - id: remove-tabs

- repo: https://github.com/python-jsonschema/check-jsonschema.git
  rev: 0.37.1
  hooks:
  - id: check-github-workflows
    files: ^\.github/workflows/[^/]+$
    types:
    - yaml
  - id: check-jsonschema
    name: Check GitHub Workflows set timeout-minutes
    args:
    - --builtin-schema
    - github-workflows-require-timeout
    files: ^\.github/workflows/[^/]+$
    types:
    - yaml
  - id: check-readthedocs

- repo: https://github.com/pre-commit/pygrep-hooks.git
  rev: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-mock-methods
  - id: python-no-eval
  - id: python-no-log-warn
  - id: rst-backticks

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v6.0.0
  hooks:
  # Side-effects:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: requirements-txt-fixer
    exclude: >-
      ^(docs/requirements|requirements-build)\.txt$

  # Non-modifying checks:
  - id: name-tests-test
    files: >-
      ^tests/[^_].*\.py$
  - id: check-added-large-files
  - id: check-case-conflict
  # disabled due to pre-commit/pre-commit-hooks#159
  # - id: check-docstring-first
  - id: check-json
  - id: check-symlinks
  - id: check-yaml
  - id: detect-private-key

  # Heavy checks:
  - id: check-ast
    exclude: >-
      ^docs/_samples/.*\.py$
  - id: debug-statements
    exclude: >-
      ^docs/_samples/.*\.py$

- repo: https://github.com/codespell-project/codespell.git
  rev: v2.4.2
  hooks:
  - id: codespell
    exclude: >-
      ^\.github/\.json-schemas/.*\.json$

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.38.0
  hooks:
  - id: yamllint
    types:
    - file
    - yaml
    args:
    - --strict

- repo: https://github.com/openstack/bashate.git
  rev: 2.1.1
  hooks:
  - id: bashate
    exclude: >-  # FIXME: drop this
      (?x)
      ^
        build-scripts/manylinux-container-image/(
          install_libffi
          |install_openssl
          |make-static-deps-dir
          |install_libssh
          |install-userspace-tools
          |openssl-version
          |install_perl
          |install_zlib
        )\.sh
      $

- repo: https://github.com/shellcheck-py/shellcheck-py.git
  rev: v0.11.0.1
  hooks:
  - id: shellcheck
    exclude: >-  # FIXME: drop this
      (?x)
      ^
        build-scripts/manylinux-container-image/(
          build_utils
          |install_libffi
          |install_openssl
          |install_libssh
          |install-userspace-tools
          |openssl-version
          |install_perl
          |install_zlib
        )\.sh
      $

- repo: https://github.com/PyCQA/flake8.git
  rev: 7.3.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-2020 ~= 1.7.0
    - flake8-annotations ~= 3.2.0
    - flake8-comprehensions ~= 3.17.0
    - flake8-cognitive-complexity ~= 0.1.0
    - flake8-docstrings ~= 1.7.0
    - flake8-length ~= 0.3.1
    - flake8-logging ~= 1.8.0
    # NOTE: `flake8-logging-format` hasn't had updates since 2024 and
    # NOTE: thus gained an unresolved incompatibility with Python 3.14.
    - flake8-logging-format ~= 2024.24.12; python_version < "3.14"
    - flake8-pytest-style ~= 2.2.0
    # NOTE: `setuptools` provides `pkg_resources` needed by
    # NOTE: `flake8-logging-format`. `setuptools` stopped being bundled
    # NOTE: in CPython starting Python 3.12. The latest version of
    # NOTE: `setuptools` that's a part of Python 3.11.14 is v79.0.1.
    - setuptools < 81; python_version < "3.14"
    - wemake-python-styleguide ~= 1.5.0
    exclude: >-
      ^docs/_samples/.*\.py$
    language_version: python3
    types_or:
    - cython
    - python
    - pyi
    - jupyter

- repo: https://github.com/MarcoGorelli/cython-lint.git
  rev: v0.19.0
  hooks:
  - id: cython-lint
    # NOTE: This linter does not have a config file so it's set up below.
    args:
    - --max-line-length
    - '160'  # matches a similar value in the .flake8 config

- repo: https://github.com/Lucas-C/pre-commit-hooks-markup.git
  rev: v1.0.1
  hooks:
  - id: rst-linter
    files: >-
      ^README\.rst$

- repo: local
  hooks:
  - id: changelogs-rst
    name: changelog filenames
    language: fail
    entry: >-
      Changelog files must be named
      ####.(
      bugfix
      | feature
      | deprecation
      | breaking
      | doc
      | packaging
      | contrib
      | misc
      )(.#)?(.rst)?
    exclude: >-
      (?x)
      ^
        docs/changelog-fragments/(
          \.gitignore
          |(\d+|[0-9a-f]{8}|[0-9a-f]{7}|[0-9a-f]{40})\.(
            bugfix
            |feature
            |deprecation
            |breaking
            |doc
            |packaging
            |contrib
            |misc
          )(\.\d+)?(\.rst)?
          |README\.rst
          |template\.j2
        )
      $
    files: ^docs/changelog-fragments/
    types: []
    types_or:
    - file
    - symlink
  - id: changelogs-user-role
    name: Changelog files should use a non-broken :user:`name` role
    language: pygrep
    entry: :user:([^`]+`?|`[^`]+[\s,])
    pass_filenames: true
    types:
    - file
    - rst

# - repo: local
#   hooks:
#   - id: pylint
#     language: system
#     name: PyLint
#     files: \.py$
#     entry: python -m pylint
#     args: []

...
