FROM quay.io/pypa/manylinux1_x86_64
MAINTAINER Python Cryptographic Authority
WORKDIR /root
RUN yum -y install prelink && yum -y clean all
RUN curl -O https://www.cpan.org/src/5.0/perl-5.24.1.tar.gz
RUN tar zxf perl-5.24.1.tar.gz && \
    cd perl-5.24.1 && \
    ./Configure -des -Dprefix=/opt/perl && \
    make -j4 && make install
ADD install_libffi.sh /root/install_libffi.sh
RUN sh install_libffi.sh manylinux1
ADD install_openssl.sh /root/install_openssl.sh
ADD openssl-version.sh /root/openssl-version.sh
RUN sh install_openssl.sh manylinux1
ADD install_virtualenv.sh /root/install_virtualenv.sh
RUN sh install_virtualenv.sh manylinux1
