name: Fedora RPMs
on:
  push:
  pull_request:

jobs:
  fedora-rpms:
    runs-on: ubuntu-latest
    container:
      image: fedora:34
    steps:
    - run: dnf install -y dnf-plugins-core rpm-build rpmdevtools rpmlint
    - run: rpmdev-setuptree
    - run: curl -o $HOME/rpmbuild/SOURCES/ansible-pylibssh-0.2.0.tar.gz https://files.pythonhosted.org/packages/20/15/5d0abfbb294034d049f7777dbcc1638e634b13dcff7687063ac8350d95a1/ansible-pylibssh-0.2.0.tar.gz
    - run: curl -o $HOME/rpmbuild/SOURCES/expandvars-0.7.0.tar.gz https://files.pythonhosted.org/packages/a4/8f/67123c5c9e63a658dffdd073c0b95a4d96e2152d1d9ffee754022360d4e1/expandvars-0.7.0.tar.gz
    - uses: actions/checkout@v2
    - run: rpmlint ./rpm.spec
    - run: rpmbuild -bs ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.src.rpm
    - run: rpmbuild -br --nodeps ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.buildreqs.nosrc.rpm
    - run: rpmbuild -br ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.buildreqs.nosrc.rpm
    - run: rpmbuild -bb ./rpm.spec
