name: Fedora RPMs
on:
  push:
  pull_request:

jobs:
  fedora-rpms:
    runs-on: ubuntu-latest
    container:
      image: fedora:34
    steps:
    - run: dnf install -y dnf-plugins-core rpm-build rpmdevtools rpmlint
    - run: rpmdev-setuptree
    - run: >-
        spectool
        --all
        --get-files
        --directory "$HOME/rpmbuild/SOURCES/"
        rpm.spec
    - uses: actions/checkout@v2
    - run: rpmlint ./rpm.spec
    - run: rpmbuild -bs ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.src.rpm
    - run: rpmbuild -br --nodeps ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.buildreqs.nosrc.rpm
    - run: rpmbuild -br ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.buildreqs.nosrc.rpm
    - run: rpmbuild -bb ./rpm.spec
