name: Fedora RPMs
on:
  push:
  pull_request:

jobs:
  fedora-rpms:
    runs-on: ubuntu-latest
    container:
      image: fedora:34
    steps:
    - run: dnf install -y dnf-plugins-core rpm-build rpmdevtools rpmlint
    - run: rpmdev-setuptree
    - uses: actions/checkout@v2
    - run: spectool --all --get-files --sourcedir rpm.spec
    - run: rpmlint ./rpm.spec
    - run: rpmbuild -bs ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.src.rpm
    - run: >-
        rpmbuild -br --nodeps ./rpm.spec || [ "$?" -eq 11 ]
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.buildreqs.nosrc.rpm
    - run: rpmbuild -br ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.fc34.buildreqs.nosrc.rpm
    - run: rpmbuild -bb ./rpm.spec
    - run: dnf install -y $HOME/rpmbuild/RPMS/x86_64/python3-ansible-pylibssh-0.2.0-1.fc34.x86_64.rpm
    - run: >-
        python3 -c 'from pylibsshext.session import Session; print(Session())'
    - name: Store RPM and SRPM as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fedora--srpm-n-rpm
        path: ~/rpmbuild/{,S}RPMS/

  centos-rpms:
    strategy:
      matrix:
        target-container:
        - centos:8
        - quay.io/centos/centos:stream8
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.target-container }}
    steps:
    - run: dnf install -y epel-release
    - run: dnf install -y dnf-plugins-core rpm-build rpmdevtools rpmlint
    - run: rpmdev-setuptree
    - uses: actions/checkout@v2
    - run: spectool --all --get-files --sourcedir rpm.spec
    - run: rpmlint ./rpm.spec
    - run: rpmbuild -bs ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.el8.src.rpm
    - run: rpmbuild -bb ./rpm.spec
    - run: dnf install -y $HOME/rpmbuild/RPMS/x86_64/python3-ansible-pylibssh-0.2.0-1.el8.x86_64.rpm
    - run: >-
        python3 -c 'from pylibsshext.session import Session; print(Session())'
    - name: Store RPM and SRPM as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target-container }}--srpm-n-rpm
        path: ~/rpmbuild/{,S}RPMS/

  rhel-rpms:
    runs-on: ubuntu-latest
    container:
      image: registry.access.redhat.com/ubi8/ubi
    steps:
    - run: dnf install -y dnf-plugins-core rpm-build
    - run: >-
        rpm -i
        https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/cmake-filesystem-3.18.2-9.el8.x86_64.rpm
        https://rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/libssh-devel-0.9.4-2.el8.x86_64.rpm
      #- run: rpmdev-setuptree  # ??
    - run: mkdir -pv ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
    - uses: actions/checkout@v2
    - run: rpmbuild --undefine=_disable_source_fetch -bs ./rpm.spec
    - run: dnf builddep -y $HOME/rpmbuild/SRPMS/python-ansible-pylibssh-0.2.0-1.el8.src.rpm
    - run: rpmbuild -bb ./rpm.spec
    - run: dnf install -y $HOME/rpmbuild/RPMS/x86_64/python3-ansible-pylibssh-0.2.0-1.el8.x86_64.rpm
    - run: >-
        python3 -c 'from pylibsshext.session import Session; print(Session())'
    - name: Store RPM and SRPM as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ubi8--srpm-n-rpm
        path: ~/rpmbuild/{,S}RPMS/
