name: Build Multi-Arch Wheels

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64, s390x] # ppc64le skipped as per pyproject.toml

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install libssh system package
        run: sudo apt-get update && sudo apt-get install -y libssh-dev

      - name: Install Python + build deps
        run: |
          pip install cibuildwheel setuptools expandvars setuptools-scm 'tomli; python_version < "3.11"' pytest pytest-cov pytest-xdist pytest-forked

      - name: Build wheels with cibuildwheel
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: cp313-* # cp39-* cp310-* cp311-* cp312-*
          CIBW_PLATFORM: linux
          CIBW_BUILD_FRONTEND: build
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.arch }}
          path: wheelhouse

      - name: Test built wheels
        run: |
          python -Im pytest -m smoke --no-cov $(pwd)/tests
